services:
  - type: web
    name: votify-backend
    runtime: java
    plan: free
    region: frankfurt
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/votify-backend-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
