spring.datasource.url=jdbc:postgresql://db.bmulgijtddwdwaajktay.supabase.co:5432/postgres?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Votify.PSW21.03
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
