server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.bmulgijtddwdwaajktay&sslmode=require}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Votify.PSW21.03}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ── Test de Categorías ───────────────────────────────────────────────────
# Cambia a true para ejecutar el runner de prueba al arrancar la aplicación
votify.test.category=false
 